from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Основная информация',callback_data='info')
btn2 = InlineKeyboardButton(text='Знаете ли Вы историю alma-mater?',callback_data='history_alma')
btn3 = InlineKeyboardButton(text='Подписаться на рассылку',callback_data='mailing')
menu.insert(btn1)
menu.insert(btn2)
menu.insert(btn3)

menu_osn = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='История',callback_data='history')
btn2 = InlineKeyboardButton(text='Наши музеи',callback_data='my_museum')
btn3 = InlineKeyboardButton(text='Прейскурант',callback_data='price')
btn4 = InlineKeyboardButton(text='Режим работы',callback_data='time_work')
btn5 = InlineKeyboardButton(text='Социальные сети',callback_data='social')
btn6 = InlineKeyboardButton(text='Назад в меню',callback_data='back_to_menu')
menu_osn.insert(btn1)
menu_osn.insert(btn2)
menu_osn.insert(btn3)
menu_osn.insert(btn4)
menu_osn.insert(btn5)
menu_osn.insert(btn6)

back = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Назад',callback_data='back_to_osn')
back.insert(btn1)

my_museums = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Музей истории Казанского университета',callback_data='museum_1')
btn2 = InlineKeyboardButton(text='Геологический музей им. А.А. Штукенберга',callback_data='museum_2')
btn3 = InlineKeyboardButton(text='Музей Казанской химической школы',callback_data='museum_3')
btn4 = InlineKeyboardButton(text='Этнографический музей',callback_data='museum_4')
btn5 = InlineKeyboardButton(text='Музей-лаборатория Е.К. Завойского',callback_data='museum_5')
btn6 = InlineKeyboardButton(text='Музей Н.И. Лобачевского',callback_data='museum_6')
btn7 = InlineKeyboardButton(text='Назад',callback_data='back_to_osn')
my_museums.insert(btn1)
my_museums.insert(btn2)
my_museums.insert(btn3)
my_museums.insert(btn4)
my_museums.insert(btn5)
my_museums.insert(btn6)
my_museums.insert(btn7)

back_to_museum = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Записаться на экскурсию',callback_data='excursion_mount')
btn2 = InlineKeyboardButton(text='Назад к музеям',callback_data='back_to_museum')
back_to_museum.insert(btn1)
back_to_museum.insert(btn2)

calendar = InlineKeyboardMarkup(row_width=7)
btn1 = InlineKeyboardButton(text='1',callback_data='1')
btn2 = InlineKeyboardButton(text='2',callback_data='2')
btn3 = InlineKeyboardButton(text='3',callback_data='3')
btn4 = InlineKeyboardButton(text='4',callback_data='4')
btn5 = InlineKeyboardButton(text='5',callback_data='5')
btn6 = InlineKeyboardButton(text='6',callback_data='6')
btn7 = InlineKeyboardButton(text='7',callback_data='7')
btn8 = InlineKeyboardButton(text='8',callback_data='8')
btn9 = InlineKeyboardButton(text='9',callback_data='9')
btn10 = InlineKeyboardButton(text='10',callback_data='10')
btn11 = InlineKeyboardButton(text='11',callback_data='11')
btn12 = InlineKeyboardButton(text='12',callback_data='12')
btn13 = InlineKeyboardButton(text='13',callback_data='13')
btn14 = InlineKeyboardButton(text='14',callback_data='14')
btn15 = InlineKeyboardButton(text='15',callback_data='15')
btn16 = InlineKeyboardButton(text='16',callback_data='16')
btn17 = InlineKeyboardButton(text='17',callback_data='17')
btn18 = InlineKeyboardButton(text='18',callback_data='18')
btn19 = InlineKeyboardButton(text='19',callback_data='19')
btn20 = InlineKeyboardButton(text='20',callback_data='20')
btn21 = InlineKeyboardButton(text='21',callback_data='21')
btn22 = InlineKeyboardButton(text='22',callback_data='22')
btn23 = InlineKeyboardButton(text='23',callback_data='23')
btn24 = InlineKeyboardButton(text='24',callback_data='24')
btn25 = InlineKeyboardButton(text='25',callback_data='25')
btn26 = InlineKeyboardButton(text='26',callback_data='26')
btn27 = InlineKeyboardButton(text='27',callback_data='27')
btn28 = InlineKeyboardButton(text='28',callback_data='28')
btn29 = InlineKeyboardButton(text='Назад к музеям',callback_data='back_to_museum')
calendar.insert(btn1)
calendar.insert(btn2)
calendar.insert(btn3)
calendar.insert(btn4)
calendar.insert(btn5)
calendar.insert(btn6)
calendar.insert(btn7)
calendar.insert(btn8)
calendar.insert(btn9)
calendar.insert(btn10)
calendar.insert(btn11)
calendar.insert(btn12)
calendar.insert(btn13)
calendar.insert(btn14)
calendar.insert(btn15)
calendar.insert(btn16)
calendar.insert(btn17)
calendar.insert(btn18)
calendar.insert(btn19)
calendar.insert(btn20)
calendar.insert(btn21)
calendar.insert(btn22)
calendar.insert(btn23)
calendar.insert(btn24)
calendar.insert(btn25)
calendar.insert(btn26)
calendar.insert(btn27)
calendar.insert(btn28)
calendar.insert(btn29)


mount = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Январь',callback_data='jan')
btn2 = InlineKeyboardButton(text='Февраль',callback_data='feb')
btn3 = InlineKeyboardButton(text='Март',callback_data='mar')
btn4 = InlineKeyboardButton(text='Апрель',callback_data='apr')
btn5 = InlineKeyboardButton(text='Май',callback_data='mai')
btn6 = InlineKeyboardButton(text='Июнь',callback_data='iun')
btn7 = InlineKeyboardButton(text='Июль',callback_data='iul')
btn8 = InlineKeyboardButton(text='Август',callback_data='avg')
btn9 = InlineKeyboardButton(text='Сентябрь',callback_data='sent')
btn10 = InlineKeyboardButton(text='Октябрь',callback_data='okt')
btn11 = InlineKeyboardButton(text='Ноябрь',callback_data='noyab')
btn12 = InlineKeyboardButton(text='Декабрь',callback_data='dec')
btn13 = InlineKeyboardButton(text='Назад к музею',callback_data='back_to_museum')
mount.insert(btn1)
mount.insert(btn2)
mount.insert(btn3)
mount.insert(btn4)
mount.insert(btn5)
mount.insert(btn6)
mount.insert(btn7)
mount.insert(btn8)
mount.insert(btn9)
mount.insert(btn10)
mount.insert(btn11)
mount.insert(btn12)
mount.insert(btn13)

time = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='10:00',callback_data='10:00')
btn2 = InlineKeyboardButton(text='11:00',callback_data='11:00')
btn3 = InlineKeyboardButton(text='12:00',callback_data='12:00')
btn4 = InlineKeyboardButton(text='13:00',callback_data='13:00')
btn5 = InlineKeyboardButton(text='14:00',callback_data='14:00')
btn6 = InlineKeyboardButton(text='15:00',callback_data='15:00')
btn7 = InlineKeyboardButton(text='16:00',callback_data='16:00')
btn8 = InlineKeyboardButton(text='17:00',callback_data='17:00')
btn9 = InlineKeyboardButton(text='Назад к музею',callback_data='back_to_museum')
time.insert(btn1)
time.insert(btn2)
time.insert(btn3)
time.insert(btn4)
time.insert(btn5)
time.insert(btn6)
time.insert(btn7)
time.insert(btn8)
time.insert(btn9)

alma = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Информация о конкурсе',callback_data='info_konkurs')
btn2 = InlineKeyboardButton(text='Викторина',callback_data='quiz')
btn3 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
alma.insert(btn1)
alma.insert(btn2)
alma.insert(btn3)

alma_back = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Назад',callback_data='back_to_alma')
alma_back.insert(btn1)

alma_quiz = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Перейти к тесту',callback_data='start_ask')
btn2 = InlineKeyboardButton(text='Посмотреть рейтинг',callback_data='rate')
btn3 = InlineKeyboardButton(text='Назад',callback_data='back_to_alma')
alma_quiz.insert(btn1)
alma_quiz.insert(btn2)
alma_quiz.insert(btn3)

mailing = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Подписаться на рассылку\отписаться от рассылки',callback_data='off_on_mailing')
btn2 = InlineKeyboardButton(text='Назад',callback_data='back_to_menu')
mailing.insert(btn1)
mailing.insert(btn2)

cancel = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Отмена',callback_data='cancel')
cancel.insert(btn1)

social = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Вконтакте',url='https://vk.com/museumskfu')
btn2 = InlineKeyboardButton(text='Instagram',url='https://www.instagram.com/museumskfu/')
btn3 = InlineKeyboardButton(text='Facebook',url='https://www.facebook.com/museumskfu/')
btn4 = InlineKeyboardButton(text='Назад',callback_data='back_to_osn')
social.insert(btn1)
social.insert(btn2)
social.insert(btn3)
social.insert(btn4)

quiz1 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Иван Михайлович Симонов',callback_data='otv11')
btn2 = InlineKeyboardButton(text='Николай Иванович Лобачевский',callback_data='otv12')
btn3 = InlineKeyboardButton(text='Алексей Зиновьевич Петров',callback_data='otv13')
quiz1.insert(btn1)
quiz1.insert(btn2)
quiz1.insert(btn3)

quiz2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Гидромеханика',callback_data='otv21')
btn2 = InlineKeyboardButton(text='Аэромеханика',callback_data='otv22')
btn3 = InlineKeyboardButton(text='Аэродинамика',callback_data='otv23')
quiz2.insert(btn1)
quiz2.insert(btn2)
quiz2.insert(btn3)

quiz3 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Иван Михайлович Симонов',callback_data='otv31')
btn2 = InlineKeyboardButton(text='Дмитрий Иванович Дубяго',callback_data='otv32')
btn3 = InlineKeyboardButton(text='Николай Алексеевич Галкин',callback_data='otv33')
quiz3.insert(btn1)
quiz3.insert(btn2)
quiz3.insert(btn3)

quiz4 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='К.Ф. Фукс',callback_data='otv41')
btn2 = InlineKeyboardButton(text='И.Н. Березин',callback_data='otv42')
btn3 = InlineKeyboardButton(text='А.Х. Халиков',callback_data='otv43')
quiz4.insert(btn1)
quiz4.insert(btn2)
quiz4.insert(btn3)

quiz5 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Сбор лекарственных растений',callback_data='otv51')
btn2 = InlineKeyboardButton(text='Пчеловодство',callback_data='otv52')
btn3 = InlineKeyboardButton(text='Выращивание томатов',callback_data='otv53')
quiz5.insert(btn1)
quiz5.insert(btn2)
quiz5.insert(btn3)

quiz6 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Рутений',callback_data='otv61')
btn2 = InlineKeyboardButton(text='Медь',callback_data='otv62')
btn3 = InlineKeyboardButton(text='Цинк',callback_data='otv63')
quiz6.insert(btn1)
quiz6.insert(btn2)
quiz6.insert(btn3)

quiz7 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Алексей Максимович Пешков',callback_data='otv71')
btn2 = InlineKeyboardButton(text='Лев Николаевич Толстой',callback_data='otv72')
btn3 = InlineKeyboardButton(text='Николай Александрович Бердяев',callback_data='otv73')
quiz7.insert(btn1)
quiz7.insert(btn2)
quiz7.insert(btn3)